name: "build"
on:
  push:
    branches:
      - win-testing
permissions:
  contents: read
jobs:
  debug:
    runs-on: windows-latest
    steps:
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\include
  t1:
    runs-on: windows-latest
    steps:
      - run: which gcc
