name: "build"
on:
  push:
    branches:
      - win-testing
permissions:
  contents: read
jobs:
  debug:
    name: Building ubuntu
    runs-on: windows=latest
    steps:
      - run: dir /s C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib
