name: "win-testing"
on:
  push:
    branches:
      - win-testing
permissions:
  contents: read
jobs:
  debug:
    runs-on: windows-latest
    steps:
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\lib
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\x86_64-w64-mingw32\include
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\include
      - run: dir C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\lib
  t1:
    runs-on: windows-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: dir C:\\Users\\runneradmin\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained
      - run: dir C:\\Users\\runneradmin\\.rustup\\toolchains\\
